### ISSUE TITLE
i dont know if its a problem on my side or the mod's but

### ISSUE THREAD

**Issue by SirWish** [remyCases/SpeedshardBackpack#1]
![image_2024-03-18_175857295](https://github.com/remyCases/SpeedshardBackpack/assets/163877941/bc6f8877-9297-421c-b0d7-9cd5a75c3d56)

**Comment by remyCases** [comment]
Could you sent me the log of MSL and the .sml file you're using (Discord is fine) ?

**Comment by remyCases** [comment]
Fix in the next release
